version: '3.8'

services:
  telegram-bot-service:
    container_name: bot
    build:
      context: ./telegram-bot-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/weatherbot_users
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345678
    depends_on:
      - db
    networks:
      - my-network

  weather-service:
    container_name: weather_service
    build:
      context: ./weather-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/weatherbot_users
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345678
    depends_on:
      - db
    networks:
      - my-network

  db:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: weatherbot_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network: