spring:
  application:
    name: telegram-bot-service
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://db:5432/weatherbot_users # change "localhost" to db while using Docker for deploying, and vice versa
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.yaml
    show-sql: true
telegram:
  bot:
    token: 7503976318:AAF2fZ5mThVyamp8X_uMtT7lwPxvA0R7xoY
    username: weather_comp_bot


